require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)

    # fix issue with arm arch, ie M1 chip
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    #   end
    # end

    # Fix for XCode 12.5 beta
    # find_and_replace('../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm',
    # '_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules', '_initializeModules:(NSArray<Class> *)modules')
  end
end

# def find_and_replace(dir, findstr, replacestr)
#   Dir[dir].each do |name|
#       text = File.read(name)
#       replace = text.gsub(findstr,replacestr)
#       if text != replace
#           puts 'Fix: ' + name
#           File.open(name, 'w') { |file| file.puts replace }
#           STDOUT.flush
#       end
#   end
#   Dir[dir + '*/'].each(&method(:find_and_replace))
# end